[tool.poetry]
name = "pandas-tidyverse-trials"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7.1, <3.10"
asttokens = "2.0.5"
backcall = "0.2.0"
Cycler = "0.10.0"
datar = "0.5.0"
debugpy = "1.4.3"
decorator = "5.1.0"
descartes = "1.1.0"
dfply = "0.3.3"
diot = "0.1.1"
dplython = "0.0.7"
entrypoints = "0.3"
executing = "0.8.1"
greenlet = "1.1.1"
inflection = "0.5.1"
ipykernel = "6.4.1"
ipython = "7.27.0"
ipython_genutils = "0.2.0"
jedi = "0.18.0"
jupyter-client = "7.0.3"
jupyter-core = "4.8.0"
kiwisolver = "1.3.2"
matplotlib = "3.4.3"
matplotlib-inline = "0.1.3"
mizani = "0.7.3"
nest-asyncio = "1.5.1"
numpy = "1.21.2"
palettable = "3.3.0"
pandas = "1.3.3"
parso = "0.8.2"
patsy = "0.5.1"
pexpect = "4.8.0"
pickleshare = "0.7.5"
Pillow = "8.3.2"
pipda = "0.4.5"
plotnine = "0.8.0"
prompt-toolkit = "3.0.20"
ptyprocess = "0.7.0"
pure-eval = "0.2.1"
Pygments = "2.10.0"
pyparsing = "2.4.7"
python-dateutil = "2.8.2"
python-slugify = "5.0.2"
pytz = "2021.1"
PyYAML = "5.4.1"
pyzmq = "22.3.0"
scipy = "1.7.1"
siuba = "0.0.25"
six = "1.16.0"
SQLAlchemy = "1.4.23"
statsmodels = "0.12.2"
text-unidecode = "1.3"
tornado = "6.1"
tqdm = "4.62.2"
traitlets = "5.1.0"
varname = "0.8.1"
wcwidth = "0.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
